// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezzhefcasphhtccpgidu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6emhlZmNhc3BoaHRjY3BnaWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTc0NzksImV4cCI6MjA2OTE5MzQ3OX0.8B7QdGt9QbiGLqy0Kas8XOBNRhFjVi5X-6WMrDUScHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});